# Generated by Django 4.2.6 on 2023-11-17 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_tbl_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_place',
            old_name='place_oin',
            new_name='place_pin',
        ),
    ]
