# Generated by Django 4.2.6 on 2024-01-14 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_tbl_breedtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_groomingtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grooming_type', models.CharField(max_length=50)),
            ],
        ),
    ]
