# Generated by Django 4.2.6 on 2023-12-27 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_tbl_hospital'),
        ('Admin', '0007_tbl_breedtype'),
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('food_rate', models.CharField(max_length=50)),
                ('food_photo', models.FileField(upload_to='ShopDoc/')),
                ('food_content', models.CharField(max_length=50)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_shop')),
                ('subc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_subcategory')),
            ],
        ),
    ]
