# Generated by Django 4.2.6 on 2023-12-27 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_tbl_breedtype'),
        ('Guest', '0004_tbl_hospital'),
        ('Shop', '0002_tbl_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_dob', models.CharField(max_length=50)),
                ('pet_rate', models.CharField(max_length=50)),
                ('pet_photo', models.FileField(upload_to='ShopDoc/')),
                ('pet_description', models.CharField(max_length=50)),
                ('breedtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_breedtype')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_shop')),
            ],
        ),
    ]
