# Generated by Django 4.2.6 on 2024-03-22 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_tbl_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_product',
            name='product_details',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
