# Generated by Django 4.2.6 on 2024-01-14 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0008_tbl_groomingtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_gdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gd_photo', models.FileField(upload_to='BoardDoc/')),
                ('gd_details', models.CharField(max_length=100)),
                ('grooming', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_groomingtype')),
            ],
        ),
    ]
