# Generated by Django 4.2.6 on 2024-01-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Petboarding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_gdetails',
            name='gd_pets',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
