# Generated by Django 4.2.6 on 2024-01-14 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_tbl_groomingtype'),
        ('Petboarding', '0002_tbl_gdetails_gd_pets'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=40)),
                ('staff_email', models.CharField(max_length=50)),
                ('staff_contact', models.CharField(max_length=15)),
                ('staff_photo', models.FileField(upload_to='BoardDoc/')),
                ('staff_address', models.CharField(max_length=60)),
                ('staff_proof', models.FileField(upload_to='BoardDoc/')),
                ('grooming', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_groomingtype')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_photo', models.FileField(upload_to='BoardDoc/')),
                ('gallery_caption', models.CharField(max_length=100)),
                ('gd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Petboarding.tbl_gdetails')),
            ],
        ),
    ]
