# Generated by Django 4.2.6 on 2024-01-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Petboarding', '0003_tbl_staff_tbl_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_staff',
            name='staff_gender',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
