# Generated by Django 4.2.6 on 2024-01-14 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_tbl_petboarding'),
        ('Petboarding', '0004_tbl_staff_staff_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_gdetails',
            name='boarding',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_petboarding'),
        ),
    ]
