# Generated by Django 4.2.6 on 2024-01-14 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_tbl_petboarding'),
        ('Petboarding', '0005_tbl_gdetails_boarding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_gdetails',
            name='boarding',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_petboarding'),
        ),
    ]
