# Generated by Django 4.2.6 on 2024-01-14 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Petboarding', '0007_alter_tbl_gdetails_boarding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_gdetails',
            name='boarding',
        ),
    ]
