# Generated by Django 4.2.6 on 2024-01-14 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Petboarding', '0008_remove_tbl_gdetails_boarding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_gallery',
            name='gd',
        ),
        migrations.DeleteModel(
            name='tbl_gdetails',
        ),
    ]
