# Generated by Django 4.2.6 on 2024-01-14 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_tbl_petboarding'),
        ('Admin', '0008_tbl_groomingtype'),
        ('Petboarding', '0009_remove_tbl_gallery_gd_delete_tbl_gdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_gdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gd_photo', models.FileField(upload_to='BoardDoc/')),
                ('gd_details', models.CharField(max_length=100)),
                ('gd_pets', models.CharField(max_length=50)),
                ('boarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_petboarding')),
                ('grooming', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_groomingtype')),
            ],
        ),
    ]
