# Generated by Django 4.2.6 on 2024-01-14 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Petboarding', '0018_tbl_gallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_gallery',
        ),
    ]
