# Generated by Django 4.2.6 on 2024-01-15 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Petboarding', '0020_tbl_gallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_gallery',
        ),
    ]
