# Generated by Django 4.2.6 on 2024-01-15 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Petboarding', '0024_tbl_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_model',
        ),
    ]
