# Generated by Django 4.2.6 on 2023-12-14 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0006_tbl_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_address', models.CharField(max_length=50)),
                ('user_cont', models.CharField(max_length=11)),
                ('user_email', models.CharField(max_length=50)),
                ('user_password', models.CharField(max_length=8)),
                ('user_photo', models.FileField(upload_to='UserPhoto/')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
