# Generated by Django 4.2.6 on 2023-12-26 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_tbl_breedtype'),
        ('Guest', '0003_alter_tbl_shop_shop_photo_alter_tbl_shop_shop_proof'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=50)),
                ('hospital_address', models.CharField(max_length=50)),
                ('hospital_contact', models.CharField(max_length=15)),
                ('hospital_email', models.CharField(max_length=50)),
                ('hospital_password', models.CharField(max_length=8)),
                ('hospital_logo', models.FileField(upload_to='HospitalDoc/')),
                ('hospital_proof', models.FileField(upload_to='HospitalDoc/')),
                ('hospital_vstatus', models.CharField(default=0, max_length=2)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
