# Generated by Django 4.2.6 on 2024-01-13 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_tbl_breedtype'),
        ('Guest', '0004_tbl_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_petboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boarding_name', models.CharField(max_length=50)),
                ('boarding_address', models.CharField(max_length=50)),
                ('boarding_contact', models.CharField(max_length=15)),
                ('boarding_email', models.CharField(max_length=50)),
                ('boarding_password', models.CharField(max_length=8)),
                ('boarding_logo', models.FileField(upload_to='BoardDoc/')),
                ('boarding_proof', models.FileField(upload_to='BoardDoc/')),
                ('boarding_status', models.CharField(default=0, max_length=2)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
