# Generated by Django 4.2.6 on 2023-12-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_tbl_complaint_complaint_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_feedback',
            name='feedback_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
