# Generated by Django 4.2.6 on 2023-12-28 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_tbl_hospital'),
        ('Hospital', '0001_initial'),
        ('User', '0005_alter_tbl_feedback_feedback_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_fordate', models.DateField(max_length=50)),
                ('appointment_fortime', models.CharField(max_length=50)),
                ('appointment_date', models.DateField(auto_now_add=True)),
                ('appointment_status', models.CharField(default=0, max_length=2)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.tbl_doctor')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_petdetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
