# Generated by Django 4.2.6 on 2024-01-06 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_alter_tbl_cart_food'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_cart',
        ),
    ]
