# Generated by Django 4.2.6 on 2024-01-14 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_tbl_petboarding'),
        ('User', '0017_tbl_booking_totalamount'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_boardingappointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_fromdate', models.DateField(max_length=50)),
                ('board_todate', models.DateField(max_length=50)),
                ('board_details', models.CharField(max_length=100)),
                ('board_date', models.DateField(auto_now_add=True)),
                ('booking_status', models.CharField(default=0, max_length=2)),
                ('boarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_petboarding')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
