# Generated by Django 4.2.6 on 2024-01-15 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Petboarding', '0026_tbl_gallery'),
        ('Guest', '0005_tbl_petboarding'),
        ('User', '0018_tbl_boardingappointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_groomingappointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gappointment_fordate', models.DateField(max_length=50)),
                ('gappointment_date', models.DateField(auto_now_add=True)),
                ('gappointment_status', models.CharField(default=0, max_length=2)),
                ('gd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Petboarding.tbl_gdetails')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_petdetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
