# Generated by Django 4.2.6 on 2024-01-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0019_tbl_groomingappointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_petdetails',
            name='pet_gender',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
