# Generated by Django 4.2.6 on 2024-01-18 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0001_initial'),
        ('Guest', '0005_tbl_petboarding'),
        ('User', '0020_tbl_petdetails_pet_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_content', models.CharField(max_length=500)),
                ('chat_time', models.DateTimeField()),
                ('chat_file', models.FileField(upload_to='ChatFiles/')),
                ('doctor_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_from', to='Hospital.tbl_doctor')),
                ('doctor_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_to', to='Hospital.tbl_doctor')),
                ('user_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_from', to='Guest.tbl_user')),
                ('user_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_to', to='Guest.tbl_user')),
            ],
        ),
    ]
