# Generated by Django 4.2.7 on 2024-02-09 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0029_tbl_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_review',
        ),
    ]
