# Generated by Django 4.2.7 on 2024-02-09 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0031_tbl_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_chat',
        ),
    ]
