# Generated by Django 4.2.6 on 2024-02-19 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_tbl_petboarding'),
        ('User', '0033_tbl_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_groomingappointment',
            name='boarding',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_petboarding'),
        ),
    ]
