# Generated by Django 4.2.6 on 2024-03-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0034_tbl_groomingappointment_boarding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_petdetails',
            name='pet_vaccinedate',
            field=models.DateField(default='Null', max_length=20),
        ),
    ]
