# Generated by Django 4.2.6 on 2023-12-27 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0004_tbl_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=50)),
                ('doctor_contact', models.CharField(max_length=12)),
                ('doctor_photo', models.FileField(upload_to='HospitalDoc/')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_hospital')),
            ],
        ),
    ]
